### ISSUE TITLE
Add example for multiple levels menu on generator

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/generator-electric#24]
The current template doesn't generate sub-level menu as example for the first usage.

**Comment by pragmaticivan** [comment]
from https://github.com/wedeploy/electric/issues/12

**Comment by zenorocha** [comment]
Thanks!

**Comment by zenorocha** [comment]
Done! https://github.com/wedeploy/generator-electric/commit/88e88dd8c5ad75e2d3deb4a45b24f25d418ea1d2
