### ISSUE TITLE
Title breaking with big name

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/generator-electric#25]
I created a project called "API Style guide" and the container for the project name breaks.

<img width="282" alt="screen shot 2017-01-25 at 10 22 26 am" src="https://cloud.githubusercontent.com/assets/301291/22303485/473b6b9a-e2e8-11e6-818a-a801ad7aba6d.png">

**Comment by pragmaticivan** [comment]
From https://github.com/wedeploy/electric/issues/11

**Comment by ygorcosta** [comment]
@pragmaticivan  I've fixed that on Marble. Can you check if it still happening?

**Comment by pragmaticivan** [comment]
It's not happening anymore http://www.guiadotrabalhoremoto.com.br/
