### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/generator-electric#26]
/blog/post-en
/blog/pt/post-pt-BR

**Comment by zenorocha** [comment]
This is very nice but I don't think we'll be able to add it in the near future :/

**Comment by pragmaticivan** [comment]
Any reason? that's pretty common for this kind of generator, and I'm already using something like that here 

http://elixirschool.com/lessons/basics/basics/
http://elixirschool.com/pt/lessons/basics/basics/

**Comment by zenorocha** [comment]
For now, it's because none of our projects need it and there are some bigger items on the backlog, but maybe in the future we can add it.
