### ISSUE TITLE
Add default script on package.json

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/generator-electric#29]
Here: https://github.com/wedeploy/generator-electric/blob/master/generators/app/templates/package.json

maybe:
`npm run build` => `gulp build`
`npm run deploy` => `gulp deploy`
`npm run server` => `gulp server`
`npm run watch` => `gulp watch`

**Comment by zenorocha** [comment]
https://github.com/electricjs/generator-electric/commit/87ca749314979f4f033dc8fbf0f26a965284a97d
