### ISSUE TITLE
Blog subpages missing top margin

### ISSUE THREAD

**Issue by ethib137** [wedeploy/generator-electric#37]
![screen shot 2017-02-17 at 4 36 26 pm](https://cloud.githubusercontent.com/assets/1609196/23088326/5c11fe94-f530-11e6-9e24-29e26e1d6a6e.png)

The subpages are missing this container `<div class="container-hybrid docs-home-top">` which the main docs page has. The margin is being added to docs-home-top, so the fix might need to be made in marble so that top margin is added to a class that doesn't contain "home".

**Comment by zenorocha** [comment]
No longer reproducible.
