### ISSUE TITLE
The main search in the /docs page has no autocomplete

### ISSUE THREAD

**Issue by jbalsas** [wedeploy/generator-electric#5]
Currently, inside the docs section, the autocomplete feature is only implemented in the sidebar search, not in the main one. Should we consider adding it there as well?

**Comment by zenorocha** [comment]
Oh yeah, thanks @jbalsas!

Could you take a look @Robert-Frampton?

**Comment by robframpton** [comment]
0582c122c240ad095ce44100c2fd5437263911d1

**Comment by jbalsas** [comment]
😂 👏 👏
